//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiapoPracticProjectGAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOnShipment
    {
        public int id { get; set; }
        public int FK_ShipmentEmployee { get; set; }
        public int FK_Product_id { get; set; }
        public int QuantityOfShipment { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ShipmentEmployee ShipmentEmployee { get; set; }
    }
}
