//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiapoPracticProjectGAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipmentEmployee()
        {
            this.ProductOnShipment = new HashSet<ProductOnShipment>();
        }
    
        public int id { get; set; }
        public int FK_Employee_id { get; set; }
        public int FK_Warehouse_id { get; set; }
        public System.DateTime DateOfShipment { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOnShipment> ProductOnShipment { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
